name: Tests

on:
    push:
        branches: [main]
    pull_request: ~

jobs:
    symfony-extension:
        name: SymfonyExtension
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./lib/symfony-extension

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v3

            - name: 'Install PHP'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '8.2'
                  tools: composer:v2
                  ini-values: date.timezone=UTC

            - name: Install dependencies
              run: |
                  composer install --no-progress
                  ./vendor/bin/simple-phpunit install
                  composer install --no-scripts --working-dir=tools/psalm

            - name: PHPUnit
              run: vendor/bin/simple-phpunit --testdox

            - name: Psalm
              run: tools/psalm/vendor/bin/psalm

    docs-build:
        name: Build docs
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: 'Install PHP'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: '8.2'
                  tools: composer:v2
                  ini-values: date.timezone=UTC

            - name: Install dependencies
              run: composer install --no-progress

            - name: Build the docs
              run: |
                  mkdir html
                  vendor/bin/guides --theme rtd --output html
